### ISSUE TITLE
Fails with newer versions of cz

### ISSUE THREAD

**Issue by cvockrodt** [OmgImAlexis/putio_client#4]
When installing with the latest version (1.8.2) of cz, node fails to run with the following error:
```
config.defaults({
       ^

TypeError: config.defaults is not a function
    at Object.<anonymous> (/opt/putio_client/app.js:11:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
Hard-coding the version to 1.3.1 allows it to run correctly. I'm not sure which version is breaking

**Comment by cvockrodt** [comment]
It looks like it fails at cz=^1.6.0
